spring.application.name=website-db-springboot
spring.servlet.multipart.enabled=true
spring.mvc.contentnegotiation.favor-parameter=true
spring.mvc.contentnegotiation.favor-path-extension=false
spring.mvc.contentnegotiation.media-types.multipart=multipart/form-data
spring.mvc.contentnegotiation.media-types.json=application/json